# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - devPostsInsightsML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://samplekr/
        username: ${{ secrets.AzureAppService_ContainerUsername_8beb9b8f982440ba80ccf9c6d8a97bf0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7919411ae6e0483fba25dd640ccfff2e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: samplekr/${{ secrets.AzureAppService_ContainerUsername_8beb9b8f982440ba80ccf9c6d8a97bf0 }}/dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devPostsInsightsML'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b30fe1f24aaf488a86b91cfa85781b2f }}
        images: 'samplekr/${{ secrets.AzureAppService_ContainerUsername_8beb9b8f982440ba80ccf9c6d8a97bf0 }}/dev:${{ github.sha }}'